title: 'Karan Sodhi'
description: 'High School Senior at Dublin Jerome. <br /> Will major in Computer Science at the University of Illinois Urbana-Champaign.  <br /> Email: sodhi.karan@outlook.com'
logo: /assets/img/logo.jpeg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
github: repository_url: http://example.com
# remote_theme: mmistakes/hpstr-jekyll-theme
