title: 'Karan Sodhi'
description: 'High School Senior at Dublin Jerome High School. Planning on majoring in computer science at the University of Illinois.  <br /> Email: sodhi.karan@outlook.com'
logo: /assets/img/logo.jpeg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
