title: 'Karan Sodhi'
description: 'High School Senior at Dublin Jerome. <br /> Will major in Computer Science at the University of Illinois Urbana-Champaign.  <br /> Email: me@karansodhi.com'
logo: /assets/img/logosmallest.jpg
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
# remote_theme: mmistakes/hpstr-jekyll-theme
